# https://drone.io

kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

trigger:
  branch:
    - master

steps:

  - name: Testing
    image: node
    commands:
      - yarn
      - yarn test

  - name: Prepare gh-pages
    image: node
    commands:
      - yarn deploy 

  - name: Deploy to gh-pages
    image: plugins/gh-pages
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_password
      pages_directory: .out/
    