# https://ci.appveyor.com

version: "{build}"

shallow_clone: true

build: off

environment:
  matrix:
    - nodejs_version: 11

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - npm run test -- -u --color